---
apiVersion: v1
kind: Secret
metadata:
  name: sinama1-sinama1-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/sinama1-gateway-gitops
